### ISSUE TITLE
Develop using new setting per period

### ISSUE THREAD

**Issue by FeSaeedi** [ehsmohammadi/Atabat#11]
Depends on #24 #27

**Comment by mmahabadi** [comment]
⌚️ Estimated Time: 16 H

**Comment by mmahabadi** [comment]
I didn't get the meaning of this issue,please describe a little more about my duty.

**Comment by ehsmohammadi** [comment]
As you know when some of our global setting is depend on period and we decided to move this attribute to period its self ( instead of some new class ) you should provide an interface for user so they can fill the period setting  
as result your task is to provide a user interface for period setting 
thank you in advance 
@mehabadi this issue is the same issue that you created instead

**Comment by ehsmohammadi** [comment]
please delete one of duplicated issue that you created
